from sqlalchemy import Column, Integer, String, Float, DateTime, ForeignKey, Text, func, UniqueConstraint
from sqlalchemy.orm import relationship
from .database import Base

# 1. Station Table: Static metadata [cite: 145]
class Station(Base):
    __tablename__ = "stations"
    
    station_id = Column(String, primary_key=True, index=True) # e.g., "BI00001" [cite: 6, 146]
    company = Column(String) # e.g., "AGIL" [cite: 7, 147]
    location = Column(String) # [cite: 148]
    
    # Relationship: One station has many fuel updates
    fuel_records = relationship("FuelData", back_populates="station")

# 2. FuelData Table: Core time-series records [cite: 152]
class FuelData(Base):
    __tablename__ = "fuel_data"
    
    id = Column(Integer, primary_key=True, index=True) 
    # timezone=True is critical on Postgres: without it, this column is
    # TIMESTAMP WITHOUT TIME ZONE, and psycopg2 silently converts any
    # timezone-aware Python datetime to the Postgres session's local
    # timezone before stripping the offset and storing it — e.g. a UTC
    # reading gets silently shifted by +1h on a server configured for
    # Africa/Tunis. timezone=True maps to TIMESTAMPTZ, which Postgres
    # always stores internally as true UTC, so this round-trips correctly
    # regardless of session timezone. (SQLite ignores this flag entirely —
    # it never had this bug — which is why it wasn't caught earlier.)
    timestamp = Column(DateTime(timezone=True), server_default=func.now())
    station_id = Column(String, ForeignKey("stations.station_id")) 
    fuel_type = Column(String) # "Gasoil50" or "SansPlomb" [cite: 8, 25, 157]
    
    # Financials and Inventory [cite: 158-162]
    price_tnd = Column(Float)
    official_price_tnd = Column(Float)
    stock_liters = Column(Float)
    capacity_liters = Column(Float)
    sales_last_5min_liters = Column(Float)
    
    station = relationship("Station", back_populates="fuel_records")

    # A given tank (station + fuel type) can only have one reading at a
    # given timestamp. This is what makes at-least-once Kafka delivery safe:
    # if the same message is processed twice (e.g. after a consumer crash
    # and restart), the second insert attempt violates this constraint
    # instead of silently creating a duplicate row.
    __table_args__ = (
        UniqueConstraint(
            "station_id", "fuel_type", "timestamp",
            name="uq_fuel_data_station_fueltype_timestamp",
        ),
    )

# 3. Alert Table: System decisions/problems [cite: 168]
class Alert(Base):
    __tablename__ = "alerts"
    
    id = Column(Integer, primary_key=True, index=True) 
    timestamp = Column(DateTime(timezone=True), default=func.now())
    station_id = Column(String, ForeignKey("stations.station_id")) 
    fuel_type = Column(String) 
    alert_type = Column(String)
    severity = Column(String)
    message = Column(String)

    # Automation-agent workflow fields (see backend/agent/watcher.py)
    status = Column(String, default="new")  # new | processing | retrying | acknowledged
    handled_by = Column(String, nullable=True)  # "agent" | "fallback" | None
    handled_at = Column(DateTime(timezone=True), nullable=True)
    # How many times the agent has picked this alert up (incremented on
    # each claim, so a crash mid-processing also counts as an attempt).
    attempts = Column(Integer, nullable=False, default=0, server_default="0")
    # When the agent may pick it up next: the retry time while "retrying",
    # the lease expiry while "processing" (if the agent dies mid-way, the
    # lease runs out and the alert is picked up again), None when "new".
    next_attempt_at = Column(DateTime(timezone=True), nullable=True)
    last_error = Column(String, nullable=True)


# 4. IncidentLog Table: Audit trail of actions taken by the automation agent
class IncidentLog(Base):
    __tablename__ = "incident_logs"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime(timezone=True), default=func.now())
    alert_id = Column(Integer, ForeignKey("alerts.id"))
    action = Column(String)  # reorder | notify_manager | escalate
    reason = Column(String)
    payload = Column(String)  # JSON-encoded snapshot of the alert context
    actor = Column(String, default="agent")


# 5. Report Table: Persisted history of LLM-generated station reports
class Report(Base):
    __tablename__ = "reports"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime(timezone=True), default=func.now())
    station_id = Column(String, ForeignKey("stations.station_id"))
    content = Column(Text)  # the full Markdown report generated by the LLM